init:
	make -C ../../ init
	pip install wheel==0.38.4
	pip install gym==0.21.0 pyglet==1.5.27 pygame matplotlib torch tensorboard

format:
	make -C ../../ format

tensorboard:
	tensorboard --logdir=runs
