name: "sb3"
policy: "MlpPolicy"
max_steps: 150000
n_steps: 1000
batch_size: 1000
n_epochs: 20
learning_rate: 0.001
gamma: 0.99
device: "cuda"
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 1.0
verbose: 1
tensorboard_log: "./cartpole_tensorboard"
